### ISSUE TITLE
/bin/bash: line 1: apt-get: command not found

### ISSUE THREAD

**Issue by FaserF** [hassio-addons/addon-debian-base#52]
# Problem/Motivation

I am getting crazy building a HA Addon with debian as based. I have already builded some Addons with the Alpine base image without issues, but Debian just wont work.

## Expected behavior

That HA builds the Addon with no issue executing the apt-get (or apt) commands.

## Actual behavior

I cant continue building the addon, as HA throws an error, that it cant find apt-get

## Steps to reproduce

Create any new HA Addon with debian as based. I even copied the Dockerfile from the Bitwarden Addon and it throws the same error. 
The strange thing is that I am running the Bitwarden Addon on the same HA OS machine.

You can find my current work here, that is not working: https://github.com/FaserF/hassio-addons/tree/dev-rocketchat/rocket.chat

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
You haven't configured the base image to use (build.json), thus it will fallback to the default images provided by the Home Assistant project (which are Alpine based)

**Comment by FaserF** [comment]
Thank you very much, such a simple mistake. Now it is working.
